#  Task 1: Data Preprocessing for Machine Learning

###  Intern Name:Adyasha Mohanty
###  Intern ID : CV/A1/64922
###  Organization: Codveda Technologies  
###  Date:  20/03/2026

---

##  Objective:
To preprocess a raw dataset by handling missing values, encoding categorical variables, scaling features, and splitting data.

##  Importing Libraries

In [4]:
import pandas as pd
import numpy as np

##  Loading Dataset

In [5]:
df = pd.read_csv('/content/1) iris.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

##  Data Understanding

In [6]:
# Basic information
df.info()

# Statistical summary
df.describe()

# Check missing values
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

##  Handling Missing Values

In [7]:
# Fill missing numerical values with mean
df.fillna(df.mean(numeric_only=True), inplace=True)

##  Encoding Categorical Variables

In [8]:
from sklearn.preprocessing import LabelEncoder

# Convert categorical column into numeric
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

##  Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler

# Separate features and target
X = df.drop('species', axis=1)
y = df['species']

# Apply scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Convert scaled data into DataFrame (for better display)
scaled_df = pd.DataFrame(
    X,
    columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
)

# Display first 5 rows of scaled data
scaled_df.head()

   sepal_length  sepal_width  petal_length  petal_width
0     -0.900681     1.032057     -1.341272    -1.312977
1     -1.143017    -0.124958     -1.341272    -1.312977
2     -1.385353     0.337848     -1.398138    -1.312977
3     -1.506521     0.106445     -1.284407    -1.312977
4     -1.021849     1.263460     -1.341272    -1.312977

##  Splitting Data

In [10]:
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Check shape of split data
print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Training data shape: (120, 4)
Testing data shape: (30, 4)

In [11]:
print("Preprocessing completed successfully!")

Preprocessing completed successfully!

---
##  Conclusion

- Loaded the dataset successfully  
- Handled missing values  
- Encoded categorical variables  
- Applied feature scaling  
- Split the dataset into training and testing sets  

The dataset is now ready for machine learning modeling.