# 📊 Task 2: Linear Regression Model

### Intern Name: Adyasha Mohanty  
### Intern ID : CV/A1/64922
### Organization: Codveda Technologies  
### Date:  26/03/2026

---

## 📌 Objective:
To build a Linear Regression model to predict house prices using machine learning techniques.

---
## 📚 Importing Libraries

In [1]:
import pandas as pd
import numpy as np

---
## 📂 Loading Dataset

In [6]:
# Load dataset (space-separated values)
df = pd.read_csv('/content/4) house Prediction Data Set.csv', delim_whitespace=True, header=None)

# Assign column names (Boston Housing dataset)
df.columns = [
    'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE',
    'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE'
]

# Display dataset
df.head()

/tmp/ipykernel_8054/1805701233.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('/content/4) house Prediction Data Set.csv', delim_whitespace=True, header=None)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

---
## 🔎 Understanding the Data

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 1 columns):
 #   Column                                                                                            Non-Null Count  Dtype
---  ------                                                                                            --------------  -----
 0    0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00  505 non-null    object
dtypes: object(1)
memory usage: 4.1+ KB

0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00    0
dtype: int64

---
## 🧹 Handling Missing Values

In [4]:
df.fillna(df.mean(numeric_only=True), inplace=True)

---
## 🎯 Defining Features and Target

In [7]:
# Features (independent variables)
X = df.drop('PRICE', axis=1)

# Target (dependent variable)
y = df['PRICE']

---
## ✂️ Splitting Data

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Training data shape: (404, 13)
Testing data shape: (102, 13)

---
## 🤖 Training Linear Regression Model

In [13]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

---
## 🔮 Making Predictions

In [14]:
y_pred = model.predict(X_test)

# Display first 5 predictions
print("Predictions:", y_pred[:5])

Predictions: [28.99672362 36.02556534 14.81694405 25.03197915 18.76987992]

---
## 📊 Model Evaluation

In [15]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R2 Score:", r2)

Mean Squared Error: 24.291119474973478
R2 Score: 0.6687594935356326

---
## ✅ Conclusion

- Successfully loaded and preprocessed the dataset  
- Built a Linear Regression model  
- Predicted house prices  
- Evaluated model using MSE and R2 score  

The model demonstrates how features influence house price prediction.